# Symbolic neural networks for cognitive capacities
[Paper](http://reason.cs.uiuc.edu/tsvi/BICA_93_Main.pdf)

In [16]:
import numpy as np

exp = np.matrix('2, 1, 1, 1; 1, 0, 0, 1') # wheels, horizontal lines, handlebars, seat
print(exp)

y1 = np.matrix('1; 0')
print(y1)
y2 = np.matrix('0; 1')
print(y2)

[[2 1 1 1]
 [1 0 0 1]]
[[1]
 [0]]
[[0]
 [1]]


In [17]:
bicycle = np.matrix('2; 1; 1; 1')
print(bicycle)
unicycle = np.matrix('1; 0; 0; 1')
print(unicycle)

[[2]
 [1]
 [1]
 [1]]
[[1]
 [0]
 [0]
 [1]]


In [18]:
pinv = np.linalg.pinv(exp)
prediction_bicycle =  pinv.transpose() * bicycle
prediction_bicycle

matrix([[  1.00000000e+00],
        [ -1.11022302e-16]])

In [25]:
bicycle_no_horizontal = np.matrix('2; 0; 1; 1')
prediction_bicycle_no_horizontal =  pinv.transpose() * bicycle_no_horizontal
prediction_bicycle_no_horizontal

matrix([[ 0.6],
        [ 0.6]])

In [26]:
bicycle_or_unicycle = np.matrix('3; 1; 1; 2')
prediction_bicycle_or_unicycle =  pinv.transpose() * bicycle_or_unicycle
prediction_bicycle_or_unicycle

matrix([[ 1.],
        [ 1.]])