# Symbolic neural networks for cognitive capacities
[Paper](http://reason.cs.uiuc.edu/tsvi/BICA_93_Main.pdf)

## Example of a more complex symbolic learning, recognition and recall

Take 3 men (Adam, Baker, Charlie) and 3 women (Diane, Edna, Fay) in a group which may hold 9 people.

Make a matrix of features. Gender (1=male, 2=female), names in distributed representation

In [64]:
%run achler_functions.py

In [65]:
import numpy as np
exp = np.zeros((9, 10))
exp_labels = []
print(exp)
print(exp.shape)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
(9, 10)


In [66]:
import math
Adam = {"name": 1}
exp, exp_labels = learn_instance([Adam,], exp, exp_labels)
print(exp)
print(exp_labels)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
['name']


Learn first property

In [67]:
Adam = {"name": 1, "gender": 1}
exp, exp_labels = learn_property([Adam,], exp, exp_labels)
print(exp)
print(exp_labels)

[[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
['name', 'gender']


In [68]:
Baker  = {"gender": 1, "name": 2}
Charlie = {"gender": 1, "name": 3}
Diane = {"gender": 2, "name": 4}
Edna = {"gender": 2, "name": 5}
Fay = {"gender": 2, "name": 6}
exp, exp_labels = learn_instance([Baker, Charlie, Diane, Edna, Fay], exp, exp_labels)
print(exp)
print(exp_labels)

[[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
['name', 'gender']


Check that each instance is recognised

In [69]:
pinv = np.linalg.pinv(exp)
pinv_transpose = pinv.transpose()
print(pinv_transpose)

[[-0.30434783  0.79710145  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.08695652  0.27536232  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.13043478 -0.24637681  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.17391304  0.55072464  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.04347826  0.02898551  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.26086957 -0.49275362  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0

In [70]:
for index in range(exp.shape[0]):
    prediction = pinv_transpose * np.matrix(exp[index]).T
    print("{} {}\t{}".format(index + 1, 
          (prediction.item( (index, 0)) == max(prediction)).item(),
          round(prediction.item( (index, 0)), 2)))

1 True	0.49
2 False	0.1
3 False	0.14
4 True	0.41
5 False	0.28
6 True	0.58
7 True	0.0
8 True	0.0
9 True	0.0
